export const cakeLOL = [
  {
    "id": 1,
    "imageCard": "https://sun9-west.userapi.com/sun9-69/s/v1/ig2/W0tNQLgSeJNKUKo8bV_-slWcBgpCwXbF38-YFvBedk-S3SwB_xscr75OVsahPhAUJ4tpuLyclmRiwjskAYuBd6NC.jpg?size=960x1280&quality=95&type=album",
    "cardTitle": "Бенто - торт (12 см)",
    "cardText": "шоколадный бисквит, банановое конфи, шоколадный крем чиз и крем чиз на сливках. Декор: сахарная печать Стоимость: 1000 руб.",
    "category": ["0", "2"],
    "rating": 5,
    "price": "Стоимость: 1000 руб.",
    "imageCarouselOne": "https://sun9-west.userapi.com/sun9-69/s/v1/ig2/W0tNQLgSeJNKUKo8bV_-slWcBgpCwXbF38-YFvBedk-S3SwB_xscr75OVsahPhAUJ4tpuLyclmRiwjskAYuBd6NC.jpg?size=960x1280&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 2,
    "imageCard": "https://sun9-east.userapi.com/sun9-32/s/v1/ig2/W1F7Vn-anWW3OEUEJ7kcVXR7GYwxqK-mpMD2nIQ290lPpgzm4Ox_6RasQrO_b6d9_BX732tHkFQZMzx25hoOy6t5.jpg?size=960x1280&quality=95&type=album",
    "cardTitle": " Бенто - торт (12 см)",
    "cardText": "На фото: ванильный бисквит, клубничное конфи, крем чиз на сливках.Декор: надпись",
    "category": ["0", "2"],
    "rating": "5",
    "price": "Стоимость: 1000 руб.",
    "imageCarouselOne": "https://sun9-east.userapi.com/sun9-32/s/v1/ig2/W1F7Vn-anWW3OEUEJ7kcVXR7GYwxqK-mpMD2nIQ290lPpgzm4Ox_6RasQrO_b6d9_BX732tHkFQZMzx25hoOy6t5.jpg?size=960x1280&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 3,
    "imageCard": "https://sun3.userapi.com/sun3-12/s/v1/ig2/A2U2VwdHku-tznxpVSdpqP4vM9toSAlhqhSmgR6OzxPrAovaZmlU9-sxL-TijbQe6fng4QluyNJ7s89LhGTLaewU.jpg?size=960x1280&quality=95&type=album",
    "cardTitle": "Бенто - торт (10 см)",
    "cardText": "На фото: ванильный бисквит, классический крем чиз. Декор: сахарная печать, надпись + сердечки.",
    "category": ["0", "2"],
    "rating": "",
    "price": "Стоимость: 900 руб.",
    "imageCarouselOne": "https://sun3.userapi.com/sun3-12/s/v1/ig2/1f6SMcfogFGQxQMF4dkTB6ne7jblZepGuIBaL_wQAlFJnd10FBusVqPCvQNqK2b7s7g5-DP6OhLpCEOSPwmU9Nj5.jpg?size=453x604&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 4,
    "imageCard": "https://sun9-east.userapi.com/sun9-24/s/v1/ig2/7iu55SRBm6tqyg-QH249x0bSBYB6dpz3YUg5C7xnw1ekQH6ZV2SFdbH1z2xMP7-tY7Di1dE4FrcDo_PtVYc_Kn9n.jpg?size=453x604&quality=95&type=album",
    "cardTitle": "Капкейки (6 шт.)",
    "cardText": "На фото: красный бархат, вишнёвое конфи и крем чиз на сливках Декор: Сердечки, мишки, посыпка.",
    "category": ["0", "4"],
    "rating": "5",
    "price": "Стоимость: 850 руб.",
    "imageCarouselOne": "https://sun9-east.userapi.com/sun9-24/s/v1/ig2/7iu55SRBm6tqyg-QH249x0bSBYB6dpz3YUg5C7xnw1ekQH6ZV2SFdbH1z2xMP7-tY7Di1dE4FrcDo_PtVYc_Kn9n.jpg?size=453x604&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 5,
    "imageCard": "https://sun9-west.userapi.com/sun9-6/s/v1/ig2/CKVqTU7ZXJvW666AyR6MHSSmyKRgmIDBQH49tn4pzjw0J9MjvkmhxRUHzhOEJKuART5-e7xX52duhZUXZgbFKgpk.jpg?size=1600x1199&quality=95&type=album",
    "cardTitle": "Торт цифра 41☺",
    "cardText": "На фото: нежные медовые коржи, крем чиз и ягодное конфи. Декор: свежая голубика, печенье Oreo, конфеты Raffaello, шоколадки, печеньки, сахарная печать. Вес: 2 кг.",
    "category": ["0", "1"],
    "rating": "7",
    "price": "Стоимость: 3100 руб.",
    "imageCarouselOne": "https://sun9-west.userapi.com/sun9-6/s/v1/ig2/CKVqTU7ZXJvW666AyR6MHSSmyKRgmIDBQH49tn4pzjw0J9MjvkmhxRUHzhOEJKuART5-e7xX52duhZUXZgbFKgpk.jpg?size=1600x1199&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 6,
    "imageCard": "https://sun9-west.userapi.com/sun9-52/s/v1/ig2/Cc6w-ovr1WVFVdT2AAENW6g2CaRVaRRfD_2_wW5MZoUDzC8rnAqVO-3zK85BJpKWpVAIMkkZwrmSG5veNbuyEajJ.jpg?size=415x604&quality=95&type=album",
    "cardTitle": "Торт в стиле 'Холодное Сердце' ",
    "cardText": " На фото:Шоколадный бисквит Крем чиз на сливках Начинка, вишнёвое конфи Вес: 2 кг.",
    "category": ["0", "1"],
    "rating": "5",
    "price": " Стоимость: 2900 руб.",
    "imageCarouselOne": "https://sun9-west.userapi.com/sun9-52/s/v1/ig2/Cc6w-ovr1WVFVdT2AAENW6g2CaRVaRRfD_2_wW5MZoUDzC8rnAqVO-3zK85BJpKWpVAIMkkZwrmSG5veNbuyEajJ.jpg?size=415x604&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 7,
    "imageCard": "https://sun9-north.userapi.com/sun9-80/s/v1/ig2/I1vrK283YII7QJ53zSoUitE5zi8VWY63gPCt7AJEcs4YM22s_zHIxgc5y66XZ-0cqbR9usVaNu5rxL5n6R6TckPq.jpg?size=1166x1280&quality=95&type=album",
    "cardTitle": "Торт 'Шоколадное мороженое'",
    "cardText": "Декор: космический корабль из мастики из кинофильма'star Trek' Вес: 1,5 кг",
    "category": ["0", "1"],
    "rating": "9",
    "price": " Стоимость 2400 руб.",
    "imageCarouselOne": "https://sun9-west.userapi.com/sun9-8/s/v1/ig2/cTPPlZw5ZSAH4n3c809APGXKpDZgCWi0lzuXDHemy47RB_3487bHB9bBozYwElST1ao_1MIDWBxcWgVAJb--Xw2f.jpg?size=1101x1280&quality=95&type=album",
    "imageCarouselTwo": "https://sun9-north.userapi.com/sun9-84/s/v1/ig2/rIRh3NbgFojSBLwbP6MtpXY0xJKmw8uUl2Oi_Bl8qUY-KAqpTuq1eh0HBkQtV3nWZANKu1I41Vf1ZHkVJDjEfBZD.jpg?size=1280x960&quality=95&type=album",
    "carouselTextOne": "",
    "carouselTextTwo": "разрез"
  }, {
    "id": 8,
    "imageCard": "https://sun9-west.userapi.com/sun9-1/s/v1/ig2/2ksih4aK9suxsnGLX0TmCXBR_E9YJkuWFOrUT66RR4tEOPMwPBfN1vH7DTbvdfkxcENkm7vF7QfQruBB3Ui3Ped6.jpg?size=1007x1280&quality=95&type=album",
    "cardTitle": " Торт 'Морковный'",
    "cardText": "Декор: фотопечать, безе, леденцы, надпись, цифра. Вес: 2 кг.",
    "category": ["0", "1"],
    "rating": "7",
    "price": "Стоимость: 3300 руб.",
    "imageCarouselOne": "https://sun9-west.userapi.com/sun9-1/s/v1/ig2/2ksih4aK9suxsnGLX0TmCXBR_E9YJkuWFOrUT66RR4tEOPMwPBfN1vH7DTbvdfkxcENkm7vF7QfQruBB3Ui3Ped6.jpg?size=1007x1280&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 9,
    "imageCard": "https://sun9-east.userapi.com/sun9-60/s/v1/ig2/sB-c_Q2u9_v9yU1wxnW2UcDA2SSydhb2Tm3tUVr0sNqESPu_d4DdLD8j9Er4P5lVDGVMAQw7g7rc6_QPw38IMlMH.jpg?size=960x1280&quality=95&type=album",
    "cardTitle": "Бенто - торт (10 см)",
    "cardText": "На фото: шоколадный бисквит, начинка, сникерс (карамель + арахис), классический крем чиз.",
    "category": ["0", "2"],
    "rating": "5",
    "price": "Стоимость: 800 руб.",
    "imageCarouselOne": "https://sun9-east.userapi.com/sun9-60/s/v1/ig2/sB-c_Q2u9_v9yU1wxnW2UcDA2SSydhb2Tm3tUVr0sNqESPu_d4DdLD8j9Er4P5lVDGVMAQw7g7rc6_QPw38IMlMH.jpg?size=960x1280&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 10,
    "imageCard": "https://sun9-west.userapi.com/sun9-37/s/v1/ig2/0aj5LNV4X5tYzP6WFgl5GpWar0gJ4KQWIosGNNMZ8mHHmJ4r1Rape2qpSzOQeMkdy2FiI8X_HowTEnh8_o4PH1Ru.jpg?size=856x1280&quality=95&type=album",
    "cardTitle": "Торт в стиле 'Босс Молокосос'",
    "cardText": "На фото: Классический бисквит Крем чиз на сливках Начинка, нежный ягодный мусс Декор: фотопечать, безе, посыпка",
    "category": ["0", "1"],
    "rating": "5",
    "price": "Стоимость: 2900 руб.",
    "imageCarouselOne": "https://sun9-west.userapi.com/sun9-37/s/v1/ig2/0aj5LNV4X5tYzP6WFgl5GpWar0gJ4KQWIosGNNMZ8mHHmJ4r1Rape2qpSzOQeMkdy2FiI8X_HowTEnh8_o4PH1Ru.jpg?size=856x1280&quality=95&type=album",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }, {
    "id": 11,
    "imageCard": "",
    "cardTitle": "",
    "cardText": "",
    "category": ["0", "2"],
    "rating": "7",
    "price": "",
    "imageCarouselOne": "",
    "imageCarouselTwo": "",
    "carouselTextOne": "",
    "carouselTextTwo": ""
  }
]